eureka:
  administrator:
    name: eureka-admin
    password: Welcome$18
  client:
    serviceUrl:
      defaultZone: http://${eureka.administrator.name}:${eureka.administrator.password}@localhost:8761/eureka
  instance:
    metadata-map:
      user:
        name: actuator-admin
        password: Welcome$18
        role: ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
