eureka:
  client:
    fetch-registry: false
  server:
    enable-self-preservation: false
security:
  oauth2:
    client:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}
spring:
  application:
    name: eureka-peer-1
server:
  port: 8761