eureka:
  client:
    fetch-registry: false
  server:
    enable-self-preservation: false
security:
  oauth2:
    client:
      client-id: eureka
      client-secret: put-secret-here
spring:
  application:
    name: eureka-peer-1
server:
  port: 8761
