language: java
dist: trusty
jdk:
  - oraclejdk8

sudo: false
install: true

notifications:
  email: false

branches:
  only:
  - master
  - development

env:
  global:
    - secure: "t5Z0YrjqvJKUd5xF4jOvxySgfMm0QE15JeE83bpFgeuCg9mdKmMQDeFTxTfYridLanoRaiMJMGbBRq7zj6REv5hxcHDApKwbkhVio10PaJteZog9zjlBXAjfJv6a69z5SDUQcqVTr7bxZAEF2CdWgmJb+resPhYEUR9q8rm3fjK5GFpsHsyu4FityDeLmuYIMaOOxmhyWk0+xty4o9KyZSV5+W52djemxOfk8cO3Fe11Vlxs6FQezsleCsgR1m3YbaLe7pkclUBukAj+JyYDhTP3LyqYlag4IFRVZBwUhpmrMBcvsvjLyQyAwkyY0Q0XP/2Q3re3IHc6HwzTkiP4O2lXHco/913leiq8dxbcKi35PjVJQ/kiUkS9AGxPigTZKwlwKAea5hmXgoGBveYnPjIwhKhKNbr2q+t3+IX4gG7ETWEkGQxzLd2GfyvNbJPNVqoUUjBvlij+XAXoSBKMCYhRTPqzgDZg4A9g3Z49FEGP6vJTEeMusbtNqsbYvQuPoMHfqHmNtrnJYbHxo4Skt/VTsDqgo3XYF39hkY0m/IoF++EEdaXY9KD+HQD+hKXriNm1Nh6qFbjWt5naIAbAhTHjZGYForyaHYmo9ne+52xPfSWaUAV3cXITeeIG3kAeJ341Y2tNIwL6kFrkXKuifaQSs9XT7kQSp7PzYo2sI5g="

addons:
  sonarcloud:
    organization: "tbmelabs-github"
    token:
      secure: ${SONAR_TOKEN}

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - "$HOME/.cache"
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
