language: java
dist: trusty
jdk:
  - oraclejdk8

sudo: false
install: true

notifications:
  email: false

branches:
  only:
  - master
  - development

addons:
  sonarcloud:
    organization: "tbmelabs-github"
    token:
      secure: "XicCVyfquanzSNztOKMG93NBCcnhlFc3XNOqZ9rpPiWVLFGEoxXcLHoKRoiXihklMumqgfRJoRMmD3NIFB4Fn3DAzo4ZUhvxgoaNjM8UcGiUhwrtyu0Xfn0V9vpNVPVDZiAeW8vG3tNdxa2k9Ro1jxD10KdcrxOObzofcqSyIJK/vko7rdL5RDjHx+XlJCl0TAgInCNQkiVyLVKavCvq3rWN7OKarlWNzMIPUV1DHNEN3Yoo9A1AcQu9rVMCwUs6afOUU2jCCxUenDxxyv8g5QYPkyeiUFsNVr6xo6uF7LfasTSBeKHTrDAiqC11nOcqg/QRYGrRa0HJI3Mgc/8L1BjFR/spTOJGh/bn4hcWgIZNYtd2MNh/7GqRtLedb4vmGSlfLSu5/YTODQOXlppFyvI+n+yNInCdsaySFWswAts7SucUt/ggmx2tsIoi3yvoCEtfCvClhBO4y0UDlgo14RQ64WzmEkchfE8NTmfeUK/f5Aa9G6u58OSys4gm+y/Xk2CMcictC0T2fenHIbEnwyJUrRq84sXbsZsz9qtqNR795kX3DALwBxk+aF3mjxI57taKmpt5G5vrW1A4XkcAjE/+fGCj1q7mvLQz/w8x0DcB6AHHir9OYMYG1X0X1c3qYlqU9nQiztJ543/h7C9VKSA5J7P1RgVcg8tOGEdc7nw="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - "$HOME/.cache"
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
