language: java
dist: trusty
jdk:
  - oraclejdk8

sudo: required
install: true

notifications:
  email: false

branches:
  only:
  - master
  - development

services:
  - docker

addons:
  sonarcloud:
    organization: "tbmelabs-github"
    token:
      secure: "XicCVyfquanzSNztOKMG93NBCcnhlFc3XNOqZ9rpPiWVLFGEoxXcLHoKRoiXihklMumqgfRJoRMmD3NIFB4Fn3DAzo4ZUhvxgoaNjM8UcGiUhwrtyu0Xfn0V9vpNVPVDZiAeW8vG3tNdxa2k9Ro1jxD10KdcrxOObzofcqSyIJK/vko7rdL5RDjHx+XlJCl0TAgInCNQkiVyLVKavCvq3rWN7OKarlWNzMIPUV1DHNEN3Yoo9A1AcQu9rVMCwUs6afOUU2jCCxUenDxxyv8g5QYPkyeiUFsNVr6xo6uF7LfasTSBeKHTrDAiqC11nOcqg/QRYGrRa0HJI3Mgc/8L1BjFR/spTOJGh/bn4hcWgIZNYtd2MNh/7GqRtLedb4vmGSlfLSu5/YTODQOXlppFyvI+n+yNInCdsaySFWswAts7SucUt/ggmx2tsIoi3yvoCEtfCvClhBO4y0UDlgo14RQ64WzmEkchfE8NTmfeUK/f5Aa9G6u58OSys4gm+y/Xk2CMcictC0T2fenHIbEnwyJUrRq84sXbsZsz9qtqNR795kX3DALwBxk+aF3mjxI57taKmpt5G5vrW1A4XkcAjE/+fGCj1q7mvLQz/w8x0DcB6AHHir9OYMYG1X0X1c3qYlqU9nQiztJ543/h7C9VKSA5J7P1RgVcg8tOGEdc7nw="

deploy:
  - provider: script
    script: mvn deploy -DskipTests
    on:
      all_branches: true

env:
  global:
    - secure: "tACEgDtPRq+jZ3mzjd7C+6UrDWbFvOhZxuZQCRgGyeEvJDWthSxC7gBh8u9FDTSB9136nh9fQXhSgkyX6/pdOi/OKKYdlAhMNr8OKiu9Iq9FV1FQqwkPRYrdol9cqIN3dyVfMoHhK9kd9J8uH8Pu1UJAQEpK26L2uOoXHNQYc+mUVThvEBNh4FqkypHp9d4/Fv59O07wftr0yLmNsTPRfQz0FKAWp8Mu5B4ePBRvg4FRlNSlAh4Lekp8kuQ0OG6Avb3lXjvSWTF4io564XOE8DUK87oMQVIJ8wx7+PMA6BOWYeKdUcCWVkRPU/0x9bplWa9YCBDLvoYcYakhqxv8ibGp9qrhM7Bzbjc1w5FJpP5lKoQXD0k8c/DXuZ02SUEA46bLKLB4ZAjgZ+9oELHRRc0wXIdxIesMYBikiiLwjrvOspMWPOX0aWMcCbAWpaUS3K9jLHo8WZhWqHa5onUAysOejmIE3CvPM5F8mI+iZlxCxKxI6hqoKTwksDAVQl0HnvPvjxiNW9mqsFsFDmSe68hZYTmJc91m+ooIMiq2iny4TaWFZD4fKiBsvgaFmXaqF2vInmklDdh0dgtgt1JjW2OZpdD2TiVL6zJpQTlTEv58eIdNzmSo0PYql2CBkFPTvJrOTGW9zUOnZDc9jxdXHFvac4zJhVHtjgneKmEPcHY="
    # ^^ DOCKER_HUB_USERNAME
    - secure: "PvsfIhzDj6ClW+TV5Chhwibhw3AxpnJVz3JLnaSY3kN5n5JpqtIvnbKEqqdO3ZYJeRZjfZEUbdtmWtLHPv4L2wG93hlM2qmR7X51wmHbYANSdKVe26Y8Esb8Lo9HNw2L8Lwby9ldZ8bYFl37exCVmjtf6KnykadRfxcyDH9+6OichU2VtroFm3EMjiBDI0M7qLKyolg3+SEzR3Uz35YDSyo4a65+XTS3+Y7QTodn7NbHOyqWzUhxnjknZmA3blwgnOcxN6Tn+ClGuISaxreTXCzNmRg0ktJVmXVUYxILmvRy+eW+Fq41QtSlPmeGgb8M+eujVivo6tC9EKeyNZOSwWLoH+5Thi7WhHRzqgPmatVqwCEMnbquPMot2m5px1ADWPaGy/r2di0b6t8Or/vEdHtJ81Bbh1TRs/GFX1EpvR5IwQ+kfURuoHfKFMEZoyXt9JyKM6VoMq0/C9Mkzj2+1TYQySLX6m6j54qh57Yyt/GH8ZHrmcMYhr0Ddfo+rz1jNRJrAyYswZ/lRRi0QtPmrTS492sS/s1K5pyn0dV5CEs4xNsDQlsqx93Cb3Ua814LjyS0JPTAiznxHyuK0a6h/opKsXxGB6oRRg2rnH9tygNjY6wCt2xMJ2JAdU6nYPIITlHYXx11ltwvzwM8ihX70Gp7YZstnHGBJM64xOLiT/A="
    # ^^ DOCKER_HUB_PASSWORD
    - secure: "KXnRH+JJI0oP1zEaVomwNk1R6kUcC0qzXeW1ZUOqBnuWAQqYGUc5Kb01OdUAc4GrtxZ85IT06v/2j+MVRwsAwX9ybB4x30p2GzLB4xVQsB1zEt1uvlJYNwMOu/p11M0f8e38+7WNlBFk2r31lbw+k8rD53LyKclZHHoHI5eLq3TnfBrgoufJiHf6vd3BwjlUZfCBBBcakdQUMEM2ISkz1oKQiJGhTAXi+wSLstencuj5ISJJSb0cDZkGqqf8yFckXJvEnMdM/C4h8se3Hth5819M97SJpQAoS1a0L7UVqZ/Lhq/qqIjoCej2vaVrhs6qqo3O3QK2YJPqQOp3U6R9ISAEez3a6rmxaWA1o4oGF0932Bhfms/eWcUmLo7vj8cjagAlcipja3JJHP78f894+H+bzotlfJOBj+jD8Im37pF3NMP70WhGw7iu563+Pzcr/jv4BZl+l+Uz2l2dbNf+5pUBj+NvQG878xzje/RxaJyfIBbiT9NEyog6SkgxGN9XVpIrYdB92/DJK02sWkr2dYeHuQyZa3hnV51Vh9CyChF/rDzucs9S1Rkxl9CvbV/lTKh7+joVhs1SwAX9GULqfMUGzsNOwfAvFBG4CRdVN/IxWZQ30e3SsJWVauU9mpD8qOkVmpkBxakkQPZpYnN2aMSE7vUDd49JEmZH1uBHFYY="
    # ^^ DOCKER_HUB_EMAIL

before_script:
  - cp .travis.settings.xml $HOME/.m2/settings.xml

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - "$HOME/.cache"
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
