language: java
dist: trusty
jdk:
  - oraclejdk8

sudo: false
install: true

notifications:
  email: false

branches:
  only:
  - master
  - development

addons:
  sonarcloud:
    organization: "tbmelabs-github"
    token:
      secure: "f8VmLTEGq/EGeBC/gNsZ0HIu5B98RLsGoKpTzAfL/PwLie3sf1qLdqtnOwXNNklQ19i5dCcBfJ46UII+OgA8hdU93mu44F8Rx2nmfMwIO8uJzfTeXBGBTVeK+6IVZ9fVg10rr/5sQ0ctoTQfCc1MRUB7KqH5aEl/CqxExOdWugXWcyfXUuttLwqOLuY6DJT4+EsT5aV9RDsGLoXDN1OrknqJG68v0Lxm3ksY8g0IiGJMagQD+g9HuNj8p1quRAHJUcVObP2qcve1m/KT2uFdKH6RhVnlXCpkhsjGtP62gB2YsvAjFMfnh9CI5hloL6YLNIFneoB9mKnRPP+BOUC3XdFiuKKPwTE5u2Yn59j5D8K1QANM9Vy5XepxohXPOpuZbGxIGDZoCI8H/EsQCMYvGCzzdJWUBDEyJzBz5QuvYFmlk2ZDYaz0N6TUPFG8sDI1NdqtWU2mmyeY81Fl9d7P6Wl0KllXfCIX06GZDuqiC79riVl0W9SryjUncLTixvM7rcxze6dKomxHyYF8CW1zSYouHkfoZytmLklk2FEDJtjVSIXu5QyEhqOaI57NmNj3kQVEuQv/2c95ACtSz3W4kmmWK6X3oLMUsen7VHdFizjfM8j/MSqjlhh3BbGpVva1iMQpg14KirecOw+LJuAmaBJRKj14OghhNarg1WVzVSg="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - "$HOME/.cache"
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
