language: java
dist: trusty
jdk:
  - oraclejdk8

sudo: false
install: true

notifications:
  email: false

branches:
  only:
  - master
  - development

env:
  global:
    - secure:""

addons:
  sonarcloud:
    organization: "tbmelabs-github"
    token:
      secure: ${SONAR_TOKEN}

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE auth_test_database;" -U postgres
  - psql -c "CREATE USER auth_test_user WITH PASSWORD 'auth_test_user_password';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE auth_test_database TO auth_test_user;" -U postgres

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Pprod

cache:
  directories:
    - "$HOME/.cache"
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
